name: auto_build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  ActualizarCorreo:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Instalar chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

          CHROME_DRIVER_VERSION=`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`

          SELENIUM_STANDALONE_VERSION=3.13.0
          SELENIUM_SUBDIR=$(echo "$SELENIUM_STANDALONE_VERSION" | cut -d"." -f-2)

          sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
          sudo echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get -y update
          sudo apt-get -y install chromium-browser

          # Install Chrome.
          sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
          sudo echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get -y update
          sudo apt-get -y install chromium-browser

          # Install ChromeDriver.
          wget -N http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip -P ~/
          unzip ~/chromedriver_linux64.zip -d ~/
          rm ~/chromedriver_linux64.zip
          sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod 0755 /usr/local/bin/chromedriver


          # Install Selenium.
          wget -N http://selenium-release.storage.googleapis.com/$SELENIUM_SUBDIR/selenium-server-standalone-$SELENIUM_STANDALONE_VERSION.jar -P ~/
          sudo mv -f ~/selenium-server-standalone-$SELENIUM_STANDALONE_VERSION.jar /usr/local/bin/selenium-server-standalone.jar
          sudo chown root:root /usr/local/bin/selenium-server-standalone.jar
          sudo chmod 0755 /usr/local/bin/selenium-server-standalone.jar

      - id: Python_pip
        name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r requirements.txt

      # - name: Run script
      - name: Ejecuta script Python con python-dotenv
        env:
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
          MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
        run: |
          python3 US/send_mail.py
          python3 US/main.py

      # Push in main

      - id: commit
        name: Commit files
        run: |
          git config --local user.name action-user
          git config --local user.email "actions@github.com"
        # git add -A
        # git commit -m "Update"
        # git push origin main
        env:
          REPO_KEY: ${{ secrets.GITHUB_TOKEN }}
          username: github-actions
