name: auto_build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  ActualizarCorreo:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Instalar chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip

          # Descargar e instalar la versión específica de Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

          wget -N https://storage.googleapis.com/chrome-for-testing-public/125.0.6422.60/win64/chromedriver-win64.zip
          unzip chromedriver_linux64.zip
          sudo mv -f chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

          # Instalar las dependencias de Python
          pip install selenium

      - id: Python_pip
        name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r requirements.txt

      # - name: Run script
      - name: Ejecuta script Python con python-dotenv
        env:
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
          MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
        run: |
          python3 US/send_mail.py
          python3 US/main.py

      # Push in main

      - id: commit
        name: Commit files
        run: |
          git config --local user.name action-user
          git config --local user.email "actions@github.com"
        # git add -A
        # git commit -m "Update"
        # git push origin main
        env:
          REPO_KEY: ${{ secrets.GITHUB_TOKEN }}
          username: github-actions
