name: Actualizar

on:
  push:
    branches: ["cron"]
  schedule:
    - cron: "49 8 * * *"

jobs:
  UpdateMail:
    runs-on: ubuntu-latest
    steps:
      - name: Chequear el código
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install chromium-chromedriver
          pip install selenium

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecuta script Python con python-dotenv
        env:
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
          MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
          LOCAL: ${{ secrets.LOCAL }}
        run: |
          python3 US/send_mail.py
          python3 US/main.py

        - name: Commit changes
          run: |
            git config --global user.name "github-actions"
            git config --global user.email "actions@github.com"
            git add -A
            git commit -m "Update files"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:cron

