name: Actualizar

on:
  push:
    branches: ["cron"]
  schedule:
    - cron: "0 10 * * *"

jobs:
  UpdateMail:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Chequear el código
        uses: actions/checkout@v2

      - name: Cache de paquetes apt
        uses: actions/cache@v3
        with:
          path: /var/cache/apt
          key: ${{ runner.os }}-apt-cache
          restore-keys: |
            ${{ runner.os }}-apt-cache

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install chromium-chromedriver

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Cache de pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Instalar dependencias de Python
        run: pip install -r requirements.txt

      - name: Ejecutar script Python con python-dotenv
        env:
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
          MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
          LOCAL: ${{ secrets.LOCAL }}
        run: |
          python3 US/send_mail.py
          python3 US/main.py

      - id: commit
        name: Commit files
        run: |
          git config --local user.name "action-user"
          git pull
          git config --local user.email "actions@github.com"
          git add -A
          git commit -m "update files"
          git push origin cron
        env:
          REPO_KEY: ${{ secrets.GITHUB_TOKEN }}
          username: github-actions
