name: auto_build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  BuildJB:
    runs-on: ubuntu-22.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - id: Python_pip
        name: Python dependencies
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r requirements.txt
      - name: Instalar chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          sudo apt-get install chromium-chromedriver
      # - name: Run script
      - name: Ejecuta script Python con python-dotenv
        env:
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          MAIL_SENDER: ${{ secrets.MAIL_SENDER }}
          MAIL_RECEIVER: ${{ secrets.MAIL_RECEIVER }}
        run: |
          python3 US/main.py
        # python3 US/send_mail.py

      # Push in main

      - id: commit
        name: Commit files
        run: git config --local user.name action-user
          git config --local user.email "actions@github.com"
          git add -A
          git commit -m "Update"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
